{{- if and (.Values.steamUser) (.Values.steamPassword) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dayz.fullname" . }}-steam
  labels:
    {{- include "dayz.labels" . | nindent 4 }}
stringData:
  username: {{ .Values.steamUser | quote }}
  password: {{ .Values.steamPassword | quote }}
{{- end }}