apiVersion: v1
kind: Service
metadata:
  name: {{ include "dayz.fullname" . }}
  labels:
    {{- include "dayz.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  selector:
    app.kubernetes.io/name: {{ include "dayz.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "UDP" }}
    {{- end }}