---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dayz-dedicated-server.fullname" . }}-server-cfg
  namespace: {{ .Release.Namespace }}
data:
  serverDZ.cfg: |
    hostname="{{ .Values.serverConfig.hostname }}";
    passwordAdmin="{{ .Values.serverConfig.passwordAdmin }}";
    enableCfgGameplayFile=1
    enableWhitelist=0;
    maxPlayers=60;
    verifySignatures=2;
    forceSameBuild=1;
    disableVoN=0;
    vonCodecQuality=20;
    disable3rdPerson=1;
    disableCrosshair=0;
    serverTime="SystemTime";
    serverTimeAcceleration=2.5;
    serverNightTimeAcceleration=20;
    serverTimePersistent=0;
    guaranteedUpdates=1;
    loginQueueConcurrentPlayers=5;
    loginQueueMaxPlayers=500;
    instanceId=1;
    storageAutoFix=1;
    motd[]=
    {
      "Under",
      "Construction"
    };
    motdInterval=1;
    maxPing=100;
    timeStampFormat="Short";
    logAverageFps=1;
    logMemory=1;
    logPlayers=1;
    logFile="server_console.log";
    adminLogPlayerHitsOnly=0;
    adminLogPlacement=0;
    adminLogBuildActions=0;
    adminLogPlayerList=0;
    enableDebugMonitor=0;
    allowFilePatching=1;
    simulatedPlayersBatch=20;
    multithreadedReplication=1;
    networkRangeClose=20;
    networkRangeNear=150;
    networkRangeFar=1000;
    networkRangeDistantEffect=4000;
    defaultVisibility=1375;
    defaultObjectViewDistance=1375;
    lightingConfig=0;
    disablePersonalLight=1;
    disableBaseDamage=0;
    disableContainerDamage=0;
    class Missions
    {
        class DayZ
        {
            template="dayzOffline.chernarusplus";
        };
    };
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dayz-dedicated-server.fullname" . }}-beserver-cfg
  namespace: {{ .Release.Namespace }}
data:
  BEServer_x64.cfg: |
    RConPassword = "{{ .Values.serverConfig.rconPassword }}";
    RestrictRCon = 1;
    RConPort = 2310;