apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "dayz-dedicated-server.fullname" . }}-restart
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.cronJob.schedule }}" # Run every 4 hours
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: {{ .Values.cronJob.serviceAccountName }}
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/{{ include "dayz-dedicated-server.fullname" . }}'