replicaCount: 1
image:
  repository: ghcr.io/jespernohr/dayz-dedicated-server
  tag: "0.1.1"
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  ports:
    game: 2302
    steam: 8766
    rcon: 2310
resources:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: "2"
    memory: "2Gi"
nodeSelector: {}
tolerations: []
affinity: {}

serverConfig:
  hostname: "YOUR HOSTNAME"
  passwordAdmin: "YOUR ADMIN PASSWORD"
  rconPassword: "YOUR RCON PASSWORD"

cronJob:
  schedule: "0 */4 * * *" # Run every 4 hours
  serviceAccountName: "dayz-svc"
